name: github-secret-display
on:
  push:
    branches:
      - github-secret-display
permissions:
  contents: read
  actions: write
  id-token: write
  issues: none
  checks: none
  deployments: none
  discussions: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  display-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Write secrets to artifact
        run: |
          echo "FOO=${{ secrets.FOO }}" > secrets.txt
      - name: Upload secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.txt
