name: Build and Publish on Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: Build
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/gsd-${{ matrix.goos }}-${{ matrix.goarch }}$EXT ./cmd
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gsd-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
